-- File generated by the BNF Converter (bnfc 2.9.3).
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language Pristinum.
module Codegen.Pristinum.Abs where

import qualified Data.String
import qualified Data.Text
import Prelude
  ( Char,
    Double,
    Integer,
    String,
  )
import qualified Prelude as C
  ( Eq,
    Ord,
    Read,
    Show,
  )

data Program = PProgram [ProgramUnit]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ProgramUnit
  = PURecord Record
  | PUBind Bind Expr
  | PUBindVoid Bind
  | PUFunction Function
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Record = RRecord RecordType IDENT [Bind]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data RecordType = RTStruct | RTUnion
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Function = FFunction IDENT [Bind] Type [Stmt]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Stmt
  = SExpr Expr
  | SBind Bind Expr
  | SBindVoid Bind
  | SIf Expr [Stmt] [ElifStmt]
  | SIfElse Expr [Stmt] [ElifStmt] [Stmt]
  | SWhile Expr [Stmt]
  | SReturn Expr
  | SReturnVoid
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data ElifStmt = ESElif Expr [Stmt]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr
  = EAssign Expr Expr
  | ELOr Expr Expr
  | ELAnd Expr Expr
  | EBOr Expr Expr
  | EBXor Expr Expr
  | EBAnd Expr Expr
  | EEqual Expr Expr
  | ENotEqual Expr Expr
  | ELess Expr Expr
  | ELessEqual Expr Expr
  | EGreater Expr Expr
  | EGreaterEqual Expr Expr
  | EBShl Expr Expr
  | EBShr Expr Expr
  | EAdd Expr Expr
  | ESubstract Expr Expr
  | EPower Expr Expr
  | EMultiply Expr Expr
  | EDivide Expr Expr
  | EMod Expr Expr
  | EIncr Expr
  | EDecr Expr
  | EPos Expr
  | ENeg Expr
  | ELNot Expr
  | EBNot Expr
  | ECast Type Expr
  | EDeref Expr
  | ERef Expr
  | ESizeof Type
  | EAlignof Type
  | EPIncr Expr
  | EPDecr Expr
  | ECall Expr [Expr]
  | EIndex Expr Expr
  | EAccess Expr Expr
  | EPAccess Expr Expr
  | ENil
  | ETrue
  | EFalse
  | EChar Char
  | EInt Integer
  | EDouble Double
  | EString String
  | EIdent IDENT
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Bind = BBind IDENT Type
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Type
  = TVoid
  | TBool
  | TChar
  | TInt8
  | TInt16
  | TInt32
  | TInt64
  | TUint8
  | TUint16
  | TUint32
  | TUint64
  | TFloat32
  | TFloat64
  | TPointer Type
  | TArray Type
  | TIdent IDENT
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype IDENT = IDENT Data.Text.Text
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)
